package dev.mew.gameofguess.GUI;

import dev.mew.gameofguess.game.Difficulties;
import dev.mew.gameofguess.game.Difficulty;
import dev.mew.gameofguess.game.Game;
import dev.mew.gameofguess.game.Scores;
import java.awt.event.ActionEvent;

/**
 * Game window
 *
 * @author Mew_
 */
public class GameWindow extends javax.swing.JFrame {

    private final String difficultyPath = "difficulties.txt";
    private final String scoresPath = "scores.txt";

    private final Scores highscores = new Scores();
    private final Difficulties difficulties = new Difficulties();

    private long guessTimerMillis = 0;
    private boolean timerRunning = false;

    private final Game game = new Game();

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        loadDifficulties();
        highscores.loadScores(scoresPath);
        guessTextField.requestFocusInWindow();

    }

    private void loadDifficulties() {
        difficulties.loadDifficulties(difficultyPath);

        // Iterate through each of the difficulties and create a button corresponding with difficulty
        for (DifficultyItem menuItem : difficulties.generateButtons()) {
            menuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    // Add action handler to change difficulty when button is pressed
                    changeDifficulty(evt, menuItem.getDifficulty());

                }
            });

            // Add the created item to the menu difficulty button
            menuDifficulty.add(menuItem);

        }
    }

    private void sendText() {
        String text = guessTextField.getText();

        // Reset the "YOU WIN!" label
        statusLabel2.setText("");

        try {
            long guessedNumber = Long.parseLong(text);

            // Start timer, and get starting time from the system.
            if (!timerRunning) {
                timerRunning = true;
                guessTimerMillis = System.currentTimeMillis();

            }
            guess(guessedNumber);

        } catch (NumberFormatException e) {
            statusLabel1.setText("That is not a number, try again.");

        }

        guessTextField.setText("");

    }

    private void guess(long number) {
        long randomNumber = game.getNumber();

        // Victory condition
        if (number == randomNumber) {
            timerRunning = false;

            // Delta time from start of game until you finished guessing.
            long timeTakenMillis = System.currentTimeMillis() - guessTimerMillis;

            int seconds = (int) (timeTakenMillis / 1000);

            // Whelp! To convert ms into S.ms takes some funny business.
            // So just substring out the last 3 chars out of the string.
            int ms = Integer.parseInt((timeTakenMillis + "").substring((timeTakenMillis + "").length() - 3));

            statusLabel1.setText("YOU WON IN " + seconds + "." + ms + " SECONDS");
            statusLabel2.setText("Type any number to play again.");

            // Reset the game for another round.
            game.reset();

        }

        if (number > randomNumber) {
            statusLabel1.setText("Lower");

        } else if (number < randomNumber) {
            statusLabel1.setText("Higher");

        }
    }

    void changeDifficulty(ActionEvent evt, Difficulty difficulty) {
        game.changeDifficulty(difficulty);
        difficultyLabel.setText("Difficulty: " + difficulty.name + " 1/" + difficulty.maxNumber);
        statusLabel1.setText("");
        statusLabel1.setText("");
        game.reset();

    }

    private void showHighscores() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HighscoreWindow window = new HighscoreWindow();
                window.setVisible(true);
                window.showScores();
                window.setVisible(true);

            }
        });
    }

// <editor-fold defaultstate="collapsed" desc="Generated Code">   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewHighscore = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();
        gamePanel = new javax.swing.JPanel();
        guessTextField = new javax.swing.JTextField();
        statusLabel1 = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileShowHighscores = new javax.swing.JMenuItem();
        fileQuit = new javax.swing.JMenuItem();
        menuDifficulty = new javax.swing.JMenu();

        addNewHighscore.setTitle("ADD NEW HIGHSCORE?");
        addNewHighscore.setMinimumSize(new java.awt.Dimension(513, 300));
        addNewHighscore.setPreferredSize(new java.awt.Dimension(513, 300));
        addNewHighscore.setSize(new java.awt.Dimension(513, 300));

        jPanel1.setMinimumSize(new java.awt.Dimension(489, 272));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ADD THIS SCORE TO HIGHSCORE TABLE?");

        yesButton.setText("YES");
        yesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesButtonMouseClicked(evt);
            }
        });

        noButton.setText("NO");
        noButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noButtonMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(73, 73, 73)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel1)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(116, 116, 116)
                            .add(yesButton)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(noButton)))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 274, Short.MAX_VALUE)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(93, 93, 93)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(18, 18, 18)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(noButton)
                        .add(yesButton))
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout addNewHighscoreLayout = new org.jdesktop.layout.GroupLayout(addNewHighscore.getContentPane());
        addNewHighscore.getContentPane().setLayout(addNewHighscoreLayout);
        addNewHighscoreLayout.setHorizontalGroup(
            addNewHighscoreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addNewHighscoreLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addNewHighscoreLayout.setVerticalGroup(
            addNewHighscoreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addNewHighscoreLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game of Guess");
        setName("gameWindow"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        guessTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guessTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessTextField.setMinimumSize(new java.awt.Dimension(100, 23));
        guessTextField.setName(""); // NOI18N
        guessTextField.setPreferredSize(new java.awt.Dimension(100, 23));
        guessTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                guessTextFieldKeyReleased(evt);
            }
        });

        statusLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        statusLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel2.setToolTipText("");
        statusLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        guessLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        guessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessLabel.setText("Guess the Number");
        guessLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        difficultyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        difficultyLabel.setText("Difficulty: EASY 1/100");

        org.jdesktop.layout.GroupLayout gamePanelLayout = new org.jdesktop.layout.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(guessLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, gamePanelLayout.createSequentialGroup()
                .add(226, 226, 226)
                .add(gamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(statusLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(statusLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(226, 226, 226))
            .add(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(difficultyLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(gamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, gamePanelLayout.createSequentialGroup()
                    .add(152, 152, 152)
                    .add(guessTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(152, 152, 152)))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(difficultyLabel)
                .add(88, 88, 88)
                .add(guessLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .add(57, 57, 57)
                .add(statusLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(91, 91, 91))
            .add(gamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, gamePanelLayout.createSequentialGroup()
                    .addContainerGap(161, Short.MAX_VALUE)
                    .add(guessTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(161, 161, 161)))
        );

        org.jdesktop.layout.GroupLayout contentPaneLayout = new org.jdesktop.layout.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(gamePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(gamePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuFile.setText("File");

        fileShowHighscores.setText("Show Highscores");
        fileShowHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileShowHighscoresActionPerformed(evt);
            }
        });
        menuFile.add(fileShowHighscores);

        fileQuit.setText("Quit");
        fileQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileQuitActionPerformed(evt);
            }
        });
        menuFile.add(fileQuit);

        menuBar.add(menuFile);

        menuDifficulty.setText("Difficulty");
        menuBar.add(menuDifficulty);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, contentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessTextFieldKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            sendText();

        }
    }//GEN-LAST:event_guessTextFieldKeyReleased

    private void fileQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileQuitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_fileQuitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        highscores.saveAll(scoresPath, "Player");

    }//GEN-LAST:event_formWindowClosing

    private void noButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noButtonMouseClicked
        // TODO add your handling code here:
        addNewHighscore.setVisible(false);

    }//GEN-LAST:event_noButtonMouseClicked

    private void yesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonMouseClicked

    private void fileShowHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileShowHighscoresActionPerformed
        // TODO add your handling code here:
        showHighscores();
    }//GEN-LAST:event_fileShowHighscoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addNewHighscore;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JMenuItem fileQuit;
    private javax.swing.JMenuItem fileShowHighscores;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JTextField guessTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDifficulty;
    private javax.swing.JMenu menuFile;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JLabel statusLabel2;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

// </editor-fold>
}
